jobs:
- job: conv
  workspace:
    clean: all
  timeoutInMinutes:  120
  pool: 'Linux-CPU'
  steps:
    - task: CmdLine@2
      inputs:
        script: |          
          LLVM_PROFILE_FILE="%p.profraw" CFLAGS="-g -fprofile-instr-generate -fcoverage-mapping" CXXFLAGS="-g -fprofile-instr-generate -fcoverage-mapping" CC=clang CXX=clang++  python3 $(Build.SourcesDirectory)/tools/ci_build/build.py --build_dir=$(Build.BinariesDirectory) --config Debug --parallel --skip_submodule_sync --build_shared_lib --enable_onnx_tests
          LLVM_PROFILE_FILE="testrunner.profraw" ./onnx_test_runner /data/models
          llvm-profdata merge -sparse  -o ort.profdata *.profraw
          llvm-cov report -instr-profile=ort.profdata onnx_test_runner -object onnxruntime_test_all  $(Build.SourcesDirectory)/include/onnxruntime $(Build.SourcesDirectory)/onnxruntime/core $(Build.SourcesDirectory)/onnxruntime/contrib_ops
        workingDirectory: $(Build.BinariesDirectory)

    - template: templates/clean-agent-build-directory-step.yml
